image: docker

services:
  - docker:dind

stages:
  - production

production:
  stage: production
  only:
    - devopstest
  script:
    - sudo docker-compose -f ./docker/docker-compose-prod.yml up -d --build
  when: manual
